### ISSUE TITLE
Please Release Version: 2.3.2

### ISSUE THREAD

**Issue by santiagomera** [webjars/coffee-script#14]
Hello, 
If possible, could you please update to version 2.3.2?
Thanks!

**Comment by jamesward** [comment]
Now that CoffeeScript is officially distributed via NPM, can you use the NPM WebJar?
```
GroupID = org.webjars.npm
ArtifactID = coffeescript
Version = 2.3.2
```

Moving this Classic WebJar to the new structure is proving to be somewhat challenging.

**Comment by santiagomera** [comment]
Yes, no problem. Didn't see it was available as an NPM WebJar, sorry.
Thank you for your great work!
